// GENERATED by factory/build-site.js from library/case-studies.json — do not edit by hand.
window.CASE_STUDIES = {
  "labels": {
    "fr": {
      "context": "Contexte",
      "problem": "Le vrai problème",
      "approach": "Approche — et pourquoi ces choix",
      "results": "Résultats",
      "stack": "Stack & méthodes",
      "doc": "Document complet",
      "cta": "Étude de cas",
      "close": "Fermer"
    },
    "en": {
      "context": "Context",
      "problem": "The real problem",
      "approach": "Approach — and why",
      "results": "Results",
      "stack": "Stack & methods",
      "doc": "Full document",
      "cta": "Case study",
      "close": "Close"
    }
  },
  "cases": {
    "arkea": {
      "accent": "#ef4444",
      "doc": "https://docs.google.com/document/d/1IMbDitXQVkhThj8OEU_OJxWEX9xzpcZg49NObkJ4sIo/edit?usp=drive_link",
      "kicker": {
        "fr": "Crédit Mutuel Arkéa · Mars 2026 → Présent",
        "en": "Crédit Mutuel Arkéa · Mar 2026 → Present"
      },
      "role": {
        "fr": "PMO Stratégique & Business Analyst — Banque de Détail",
        "en": "Strategic PMO & Business Analyst — Retail Banking"
      },
      "context": {
        "fr": "~174 projets actifs, trois niveaux de lecture (chefs de projet, Management, COMEX). Mission de transformation 12-18 mois, temporaire par nature ; données éclatées, sans source de vérité partagée.",
        "en": "~174 active projects, three reading levels (project leads, Management, COMEX). A temporary 12-18 month transformation engagement; scattered data with no shared source of truth."
      },
      "problem": {
        "fr": "La demande affichée : « un outil de suivi ». Le vrai objectif : rendre les arbitrages de portefeuille visibles et traçables pour trois publics aux besoins opposés — et laisser un système que le métier maintient seul, après mon départ.",
        "en": "The stated ask: a tracking tool. The real objective: make portfolio trade-offs visible and traceable for three audiences with opposing needs — and leave a system the business maintains on its own, after I'm gone."
      },
      "approach": {
        "fr": [
          "Modéliser avant de coder : acteurs, flux de données, vraies décisions.",
          "Contrainte = direction de conception : vanilla JS strict dans le sandbox Apps Script.",
          "Maintenable par le métier : la donnée vit dans une feuille de config éditable.",
          "Confidentialité par rôle : arbitrages sensibles recalculés côté serveur.",
          "Architecture modulaire (8 fichiers) + analyse d'impact avant chaque changement."
        ],
        "en": [
          "Model before coding: actors, data flows, the real decisions.",
          "Constraint = design direction: strict vanilla JS inside the Apps Script sandbox.",
          "Maintainable by the business: data lives in an editable config sheet.",
          "Role-based confidentiality: sensitive trade-offs recomputed server-side.",
          "Modular 8-file architecture + impact analysis before every change."
        ]
      },
      "results": {
        "fr": [
          "Pilotage de portefeuille industrialisé : Kanban, KPI, jalons, alertes, comités automatisés.",
          "Traçabilité des décisions sur 3 niveaux de gouvernance.",
          "Gain capacitaire ~1 ETP/an, valorisation 31-135 k€/an.",
          "Système maintenable par le métier — objectif « après mon départ » atteint par design."
        ],
        "en": [
          "Industrialized portfolio steering: Kanban, KPIs, milestones, alerts, automated committees.",
          "Decision traceability across 3 governance levels.",
          "Capacity gain ~1 FTE/year, value €31-135k/year.",
          "System maintainable by the business — the after-I'm-gone goal met by design."
        ]
      },
      "stack": [
        "PMO",
        "Apps Script",
        "Business Analysis",
        "Kanban / KPI",
        "Analyse d'impact",
        "Gouvernance"
      ]
    },
    "velocity": {
      "accent": "#f59e0b",
      "doc": "",
      "kicker": {
        "fr": "Velocity Lab · Janvier 2026 → Présent",
        "en": "Velocity Lab · January 2026 → Present"
      },
      "role": {
        "fr": "Founder — Conseil en stratégie",
        "en": "Founder — Strategy consulting"
      },
      "context": {
        "fr": "Cabinet personnel de conseil mené en parallèle des missions : PMO augmenté, transformation et systèmes d'agents IA auditables pour structurer les décisions complexes.",
        "en": "Personal consulting practice run alongside client missions: augmented PMO, transformation and auditable AI-agent systems to structure complex decisions."
      },
      "problem": {
        "fr": "Industrialiser une pratique reproductible : passer d'un savoir-faire personnel à un système qui produit, contrôle et documente la décision avec des gates explicites.",
        "en": "Industrialize a repeatable practice: turn personal know-how into a system that produces, controls and documents decisions with explicit gates."
      },
      "results": {
        "fr": [
          "Chaîne agentique : contexte indexé, analyse d'impact, exécution par phases, validation finale humaine.",
          "Boucle qualité (revue contradictoire) avant tout livrable.",
          "Positionnement « systèmes de décision » porté sur l'ensemble des supports."
        ],
        "en": [
          "Agentic chain: indexed context, impact analysis, phased execution, final human validation.",
          "Quality loop (adversarial review) before any deliverable.",
          "A decision-systems positioning carried across every support."
        ]
      },
      "stack": [
        "Stratégie",
        "PMO augmenté",
        "AI Delivery",
        "Impact Analysis",
        "Conseil"
      ]
    },
    "neosoft": {
      "accent": "#3b82f6",
      "doc": "https://docs.google.com/document/d/1xxzyoGqOU6SiQq8ci9xPORed7DPamUyGA2Xxg_xhwEA/edit?usp=drive_link",
      "kicker": {
        "fr": "NeoSoft · Oct 2025 → Déc 2025",
        "en": "NeoSoft · Oct 2025 → Dec 2025"
      },
      "role": {
        "fr": "Product Owner — MVP application interne",
        "en": "Product Owner — Internal app MVP"
      },
      "context": {
        "fr": "Phase d'idéation et de cadrage amont d'une application interne MVP, pour valider de nouveaux parcours et fonctionnalités métier.",
        "en": "Early ideation and framing of an internal MVP app, to validate new user journeys and business features."
      },
      "problem": {
        "fr": "Sécuriser la valeur métier et l'ergonomie avant de lancer l'ingénierie : éviter de développer la mauvaise chose.",
        "en": "Secure business value and usability before engineering: avoid building the wrong thing."
      },
      "results": {
        "fr": [
          "Prototype Figma livré en collaboration étroite design-dev.",
          "POC validé + backlog Kanban priorisé.",
          "Roadmap MVP claire, exploitable sans rétro-cadrage."
        ],
        "en": [
          "Figma prototype delivered in close design-dev collaboration.",
          "POC validated + prioritized Kanban backlog.",
          "Clear MVP roadmap, usable with no re-framing."
        ]
      },
      "stack": [
        "Product Owner",
        "Design Thinking",
        "Figma",
        "UX / UI",
        "Backlog Kanban"
      ]
    },
    "thales": {
      "accent": "#a855f7",
      "doc": "https://docs.google.com/document/d/13LURIzIYDEVGRZU5gprV16Lhpt4zj_yfUqO1joVTVhw/edit?usp=drive_link",
      "kicker": {
        "fr": "Thales ISR (via MIGSO-PCUBED) · Oct 2024 → Oct 2025",
        "en": "Thales ISR (via MIGSO-PCUBED) · Oct 2024 → Oct 2025"
      },
      "role": {
        "fr": "PMO & Support Bid Management — Défense multi-milieux",
        "en": "PMO & Bid Management Support — Multi-domain Defense"
      },
      "context": {
        "fr": "Environnement Défense intense (Terre/Naval/Aéro/Espace), portefeuille de +50 offres, budgets unitaires jusqu'à >1Md€.",
        "en": "High-intensity Defense environment (Land/Naval/Air/Space), a +50-bid portfolio, unit budgets up to >€1Bn."
      },
      "problem": {
        "fr": "Fiabiliser financièrement les chiffrages et industrialiser la gestion des risques pour 4 Bid Managers, sans ralentir le tempo des offres.",
        "en": "Make quotes financially reliable and industrialize risk handling for 4 Bid Managers, without slowing the bid tempo."
      },
      "approach": {
        "fr": [
          "Analyse RC/NRC, facilitation ROR, templates QDV/MS Project.",
          "Industrialisation Excel/VBA de la gestion des risques.",
          "Audit stratégique RETEX mandaté par la GBU ISR."
        ],
        "en": [
          "RC/NRC analysis, ROR facilitation, QDV/MS Project templates.",
          "Excel/VBA industrialization of risk handling.",
          "Strategic RETEX audit mandated by the ISR GBU."
        ]
      },
      "results": {
        "fr": [
          "Traitement des risques : 3h → 15 min/offre (-92%).",
          "Rapport RETEX livré au CODIR ; « au-dessus des attentes sur 7 livrables / 10 ».",
          "Key User change management sur 2 projets Groupe."
        ],
        "en": [
          "Risk handling: 3h → 15 min/bid (-92%).",
          "RETEX report delivered to CODIR; above expectations on 7 deliverables out of 10.",
          "Change-management Key User on 2 Group projects."
        ]
      },
      "stack": [
        "PMO",
        "Bid Management",
        "RC / NRC",
        "Excel / VBA",
        "Gestion des risques",
        "RETEX"
      ]
    },
    "epsi": {
      "accent": "#10b981",
      "doc": "https://docs.google.com/document/d/18pWjCAtyOMRExgEGMnvHBI772hxGsIZtfomSjvaS4t4/edit?usp=drive_link",
      "kicker": {
        "fr": "EPSI (client Capgemini) · Avr 2024 → Juil 2024",
        "en": "EPSI (Capgemini client) · Apr 2024 → Jul 2024"
      },
      "role": {
        "fr": "Product Owner + Coach Agile — CRM sécurisé",
        "en": "Product Owner + Agile Coach — Secure CRM"
      },
      "context": {
        "fr": "MVP d'un CRM sécurisé, architecture N-tiers (Java 21 / Spring Boot 3.3), double rôle PO + Coach sur 2 équipes.",
        "en": "Secure CRM MVP, N-tier architecture (Java 21 / Spring Boot 3.3), dual PO + Coach role across 2 teams."
      },
      "problem": {
        "fr": "Livrer un MVP en moins de 2 mois tout en montant 2 équipes en maturité agile, simultanément.",
        "en": "Deliver an MVP in under 2 months while bringing 2 teams up the agile maturity curve, simultaneously."
      },
      "results": {
        "fr": [
          "Seul PO ayant livré ses 2 équipes (sur 5).",
          "MVP livré < 2 mois.",
          "Félicitations du jury (Lead Tech Capgemini + Expert Cyber Orange)."
        ],
        "en": [
          "Only PO to deliver both teams (out of 5).",
          "MVP delivered in < 2 months.",
          "Commended by the panel (Capgemini Lead Tech + Orange Cyber expert)."
        ]
      },
      "stack": [
        "Product Owner",
        "Coaching Agile",
        "Scrum",
        "User Stories",
        "Tests Postman"
      ]
    },
    "gestion-locative": {
      "accent": "#f97316",
      "doc": "https://docs.google.com/document/d/1ol-LDjmEQJhorYPO4kL01Zx-NNv1tXec8wUHrufqFgg/edit?usp=drive_link",
      "kicker": {
        "fr": "Indépendant (EI) · Juil 2022 → Sept 2023",
        "en": "Self-employed · Jul 2022 → Sep 2023"
      },
      "role": {
        "fr": "Project Manager — Gestion locative saisonnière",
        "en": "Project Manager — Seasonal rental management"
      },
      "context": {
        "fr": "Gestion d'actifs locatifs courte durée (AirBnB) en autonomie totale, du cycle locatif à la relation client.",
        "en": "Short-term rental asset management (AirBnB) in full autonomy, from the rental cycle to client relations."
      },
      "results": {
        "fr": [
          "Cycle locatif piloté de bout en bout, en autonomie.",
          "Coordination logistique, maintenance et asset management.",
          "Taux d'occupation >90% en haute saison, satisfaction 88%."
        ],
        "en": [
          "End-to-end rental cycle steered, autonomously.",
          "Logistics, maintenance and asset-management coordination.",
          "Occupancy >90% in high season, 88% satisfaction."
        ]
      },
      "stack": [
        "Asset Management",
        "Coordination",
        "Relation client",
        "Ops AirBnB"
      ]
    },
    "shuhan": {
      "accent": "#ec4899",
      "doc": "https://docs.google.com/document/d/1YrwQRrBlTZ2I9lxNmwhOv0kSdqsAalw34sNbqmhaTbk/edit?usp=drive_link",
      "kicker": {
        "fr": "Sichuan Shuhan Plastics (Chine) · Juin 2015 → Janv 2020",
        "en": "Sichuan Shuhan Plastics (China) · Jun 2015 → Jan 2020"
      },
      "role": {
        "fr": "Resp. Développement Commercial International",
        "en": "Head of International Business Development"
      },
      "context": {
        "fr": "PME industrielle chinoise sur-dépendante de son marché domestique, export limité à 5% du CA. Poste exercé 100% en anglais.",
        "en": "Chinese industrial SME over-dependent on its domestic market, exports limited to 5% of revenue. Role operated 100% in English."
      },
      "problem": {
        "fr": "Construire une force de vente export from-scratch sur des marchés émergents asiatiques culturellement hétérogènes.",
        "en": "Build an export sales force from scratch across culturally heterogeneous emerging Asian markets."
      },
      "results": {
        "fr": [
          "Part export 5% → 20% du CA (~15M$ en 2019).",
          "Management d'une équipe multiculturelle de 5.",
          "Présence opérée sur 7 marchés (Chine, Malaisie, Cambodge, Indonésie…)."
        ],
        "en": [
          "Export revenue 5% → 20% of total (~$15M in 2019).",
          "Managed a multicultural team of 5.",
          "Presence operated across 7 markets (China, Malaysia, Cambodia, Indonesia…)."
        ]
      },
      "stack": [
        "Business Dev International",
        "Management interculturel",
        "SAP Ariba",
        "Export"
      ]
    },
    "vacorda": {
      "accent": "#06b6d4",
      "doc": "https://docs.google.com/document/d/1PTNCRD_HBE4nENYdqwEFyFRPh0hM-eWsMrAhi75rGIM/edit?tab=t.0",
      "kicker": {
        "fr": "Vacorda Instruments (Chine) · Janv 2015 → Juin 2015",
        "en": "Vacorda Instruments (China) · Jan 2015 → Jun 2015"
      },
      "role": {
        "fr": "Chargé de Stratégie Digitale & Business Dev",
        "en": "Digital Strategy & Business Development"
      },
      "context": {
        "fr": "Création d'un écosystème digital from-scratch pour conquérir la zone francophone. Poste exercé 90% en anglais.",
        "en": "Built a digital ecosystem from scratch to win French-speaking markets. Role operated 90% in English."
      },
      "results": {
        "fr": [
          "Écosystème digital créé from-scratch (SEO/SEA, lead gen).",
          "Budget publicitaire 24k$/an piloté (Google Ads).",
          "Génération de leads sur la zone francophone."
        ],
        "en": [
          "Digital ecosystem built from scratch (SEO/SEA, lead gen).",
          "$24k/year ad budget steered (Google Ads).",
          "Lead generation across French-speaking markets."
        ]
      },
      "stack": [
        "Stratégie digitale",
        "SEO / SEA",
        "Google Ads",
        "Lead Generation"
      ]
    },
    "diadom": {
      "accent": "#eab308",
      "doc": "https://docs.google.com/document/d/1PTNCRD_HBE4nENYdqwEFyFRPh0hM-eWsMrAhi75rGIM/edit?usp=drive_link",
      "kicker": {
        "fr": "Diadom SAS · Sept 2012 → Oct 2014",
        "en": "Diadom SAS · Sep 2012 → Oct 2014"
      },
      "role": {
        "fr": "Chef de Projet Digital / Business Analyst",
        "en": "Digital Project Manager / Business Analyst"
      },
      "context": {
        "fr": "MOE d'une refonte e-commerce sponsorisée par la direction générale, reporting CODIR.",
        "en": "Lead on an e-commerce redesign sponsored by top management, CODIR reporting."
      },
      "results": {
        "fr": [
          "Refonte e-commerce livrée dans les jalons (chemin critique MS Project).",
          "SEO/SEA 30 k€/an piloté.",
          "Trafic +196% · conversion +23% sur 2 ans."
        ],
        "en": [
          "E-commerce redesign delivered on milestones (MS Project critical path).",
          "€30k/year SEO/SEA steered.",
          "Traffic +196% · conversion +23% over 2 years."
        ]
      },
      "stack": [
        "Chef de projet",
        "Business Analysis",
        "MS Project",
        "SEO / SEA",
        "Reporting CODIR"
      ]
    },
    "justrade": {
      "accent": "#ef4444",
      "doc": "https://docs.google.com/document/d/1JaOHl9brR_uOtd7ZPcN10GEvG5e1CPWp11Ufm67uctM/edit?usp=drive_link",
      "kicker": {
        "fr": "Justrade International (Chine) · Sept 2011 → Août 2012",
        "en": "Justrade International (China) · Sep 2011 → Aug 2012"
      },
      "role": {
        "fr": "Chargé de Projet Webmarketing — International",
        "en": "Web Marketing Project Officer — International"
      },
      "context": {
        "fr": "Coordination d'une refonte web multilingue et du social media bilingue EN/FR à l'international.",
        "en": "Coordinating a multilingual web redesign and bilingual EN/FR social media internationally."
      },
      "results": {
        "fr": [
          "Refonte multilingue coordonnée (prestataires, traducteurs).",
          "Social media bilingue EN/FR opéré.",
          "Reporting mensuel CODIR + recommandation LinkedIn client."
        ],
        "en": [
          "Multilingual redesign coordinated (vendors, translators).",
          "Bilingual EN/FR social media operated.",
          "Monthly CODIR reporting + client LinkedIn recommendation."
        ]
      },
      "stack": [
        "Webmarketing",
        "Coordination",
        "Social Media",
        "International"
      ]
    }
  }
};
