#!/usr/bin/env bun
// build-site.js — generate the site's case-study data from the library SSOT.
// Reads library/case-studies.json → writes ./case-studies.js (window.CASE_STUDIES),
// consumed by index.html. Run after editing the JSON:  bun factory/build-site.js
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dir, "..");
const src = JSON.parse(readFileSync(join(ROOT, "library/case-studies.json"), "utf8"));
const data = { labels: src.labels, cases: src.cases };

const out = `// GENERATED by factory/build-site.js from library/case-studies.json — do not edit by hand.\nwindow.CASE_STUDIES = ${JSON.stringify(data, null, 2)};\n`;
writeFileSync(join(ROOT, "case-studies.js"), out);
console.log("✓ Site case-studies →", join(ROOT, "case-studies.js"), `(${Object.keys(src.cases).length} cases)`);
